k8s-box:
    box:
        base: fedora
    k8s-box-candy:
        candy:
            - '@github.com/overthinkos/overthink/candy/supervisord:v2026.166.1222'
            - '@github.com/overthinkos/overthink/candy/k8s-layer:v2026.166.1222'
